/*
* Copyright (c) 2025 The LineageOS Project
* SPDX-License-Identifier: GPL-2.0-only
*/

#define CONFIG_TOUCHSCREEN_SYNA_TCM2 1
#define CONFIG_TOUCHSCREEN_XIAOMI_TOUCHFEATURE 1
#define CONFIG_TRUSTED_TOUCH 1
#define CONFIG_TOUCH_THP_SUPPORT 1
#define CONFIG_TOUCH_FOD_SUPPORT 1
#define CONFIG_TOUCH_SPI_CS_CLK_DELAY 1